### ISSUE TITLE
react-native support/example

### ISSUE THREAD

**Issue by alidcastano** [wagerfield/onno#53]
have you considered react-native support? i.e. by allowing custom components

though from glancing at API it's just a style function that you can compose - haven't tried it out yet - but opening this issue in case there's anything you think that's web specific that would prevent native support

**Comment by wagerfield** [comment]
Thanks for starting the discussion @alidcastano.

I don't have any direct experience with React Native, but looking at the [style API](https://facebook.github.io/react-native/docs/style) I don't see any reason why onno wouldn't work straight out of the box. 

React Native is ideal for libraries like onno and Styled System since you style components using JS with plain old CSS properties in lowerCamelCase, so no CSS in JS library is necessary.

Below is some pseudo code of how I would create the classic `Box` component using React Native and onno. I haven't tested it, so wouldn't expect it to work first time, but hopefully it won't need too much tweaking:

```jsx
import React from "react"
import { View } from "react-native"
import { omit, colorSet, spaceSet } from "onno"

// Create composed render function
// with all the style props you want
const boxSet = compose({
  name: "box",
  renderers: [
    colorSet,
    spaceSet
  ]
})

// Create omit filter function for
// removing any boxSet style props
const omitBoxProps = omit({
  renderers: [boxSet]
})

export const Box = (props) => {
  const viewStyle = boxSet(props) // render style objects
  const viewProps = omitBoxProps(props) // sanitise props
  return <View style={viewStyle} {...viewProps} />
}
```

I'll close this for now since I believe the above example is enough to get you started, but please don't hesitate to comment or reopen if necessary.
