### ISSUE TITLE
Question: any interest in helping out with core Styled System?

### ISSUE THREAD

**Issue by jxnblk** [wagerfield/onno#54]
Hi! 👋 Not sure if we've crossed paths before or not, but someone recently pointed this project out, and I wanted to say it looked cool! 

Not sure if you've been following along the recent releases of Styled System or our new project [Theme UI](https://github.com/system-ui/theme-ui), but was wondering if you'd be interested in helping out with any of that. In particular, I'm looking into ways to leverage TypeScript and generally make Styled System a better experience for people who use TS. If you're at all interested, I'm happy to outline some of the changes. The `prop-types` dependency is gone so it is truly framework-agnostic library now, for example.

(P.S. FWIW, I'm pretty sure Styled System's responsive array props predates Facepaint by a few months at least)

**Comment by peduarte** [comment]
Yes! <3

You guys both count on my help too.

**Comment by wagerfield** [comment]
Hey Brent, really appreciate you taking the time to check this project out, it's a true honour!

I just took another look at Styled System and can see v5 has come on a long way since v4 when I looked at it a couple of months ago. Great to see that a number of features I introduced to onno are also in Styled System now—I don't know if that's by coincidence or you saw what I had been doing? Also great to see that SS is now framework agnostic—I'll update the onno features doc to reflect all these changes...it'll be a lot shorter now for sure! 😄 

I wasn't sure who came up with responsive props first, so I just went off some commit dates and thought Facepaint preceded Styled System. Looking at this again I can see that the first commit to Styled System was June 2017 and Facepaint was October 2017, so I clearly got this wrong the first time around—apologies. I'll update the onno docs accordingly.

Regarding helping out with Styled System, Theme UI et al—I'd love to. The work you've been doing in this area is really innovative and a true joy to work with. I learnt a lot writing onno and was going to attempt a v2 (not that I've tagged onno as v1 yet) with improved typings and implement a config object type approach as I see you have done in v5 as it'll make onno smaller. Unlikely onno will ever be as small as SS due to the get/resolve methods and array key logic for props, styles and themes—but I reckon this approach would bring it from 5kb gzipped to under 4kb.

However, I don't think I'll be able to assist for a month or so since I just started paternity leave a week ago (hence the delay in getting back to you) and don't plan on doing much work beyond updating onno where I can so I can spend some quality time my family and newborn.

Happy to get in touch with you when I decide to return to work and see where you are with everything. Ahead of that, I'm also happy to jump on a call with you or something like that to share my learnings with you if that would be helpful?

Also thanks for offering to help out too @peduarte—more the merrier!

**Comment by wagerfield** [comment]
@jxnblk I also wanted to commend you on the `css` and `jsx` modules you created for Styled System—awesome work!

Funnily enough, I too had implemented the `css` and `style` prop to the same effect for a [component library I created for a client](https://github.com/wagerfield/xrc) called `xrc` (WIP) but hadn't thought about formalising this into a standalone package—great idea!

Also love the really simple idea of overriding Emotion's `jsx` pragma—genius 😄

**Comment by wagerfield** [comment]
Docs are now updated and I've pushed and tagged the current version of onno as v1.0.0 🎉 

I'll close this for now and get in touch when I return to work. 

Feel free to DM me on Twitter or message me in here if you wanna chat ahead of then.
